USE MERCADO_01

alter PROCEDURE p_REMOVER_VENDA(@VALOR AS DECIMAL(10,2), @NOME AS VARCHAR(60), @VEN_ID AS INT)
 AS
 UPDATE TBL_CLIENTE SET CLI_DIVIDA += @VALOR WHERE CLI_NOME = @NOME
 DELETE TBL_PAGAMENTO WHERE VENDA_ID= @VEN_ID
 DELETE TBL_ITEM_VENDA WHERE VEN_ID = @VEN_ID
 DELETE TBL_VENDA WHERE VEN_ID = @VEN_ID
 GO

create PROCEDURE p_REMOVER_ITEM(@NOME_CLIENTE VARCHAR(60), @VENDAID INT, @PRODID INT, @QTDREMOVER INT, @QTD_TOTAL_ITEM INT, @VALOR_TOTAL_VENDA DECIMAL(10,2), @VALOR_TOTAL_ITEM DECIMAL(10,2), @ITEM_VENDA_ID INT)
AS

DECLARE @DINHEIRO DECIMAL(10,2)
DECLARE @VALORUNITARIO DECIMAL(10,2) =  @VALOR_TOTAL_ITEM / @QTD_TOTAL_ITEM
DECLARE @VALORREMOVER DECIMAL(10,2) =  @VALORUNITARIO * @QTDREMOVER
DECLARE @VALORDEDOISPAGAMENTOS DECIMAL(10,2)  

SELECT @DINHEIRO = (SELECT PAG_DINHEIRO FROM TBL_PAGAMENTO WHERE VENDA_ID = @VENDAID);
UPDATE TBL_CLIENTE SET CLI_DIVIDA += @VALORREMOVER WHERE CLI_NOME = @NOME_CLIENTE
UPDATE TBL_VENDA SET VEN_TOTAL = VEN_TOTAL - @VALORREMOVER, VEN_QTD -= @QTDREMOVER WHERE VEN_ID = @VENDAID

IF(@QTDREMOVER < @QTD_TOTAL_ITEM)
BEGIN
UPDATE TBL_ITEM_VENDA SET ITEM_QTD -= @QTDREMOVER, ITEM_VALOR -= @VALORREMOVER WHERE PROD_ID = @PRODID AND VEN_ID = @VENDAID AND ITEM_VENDA_ID = @ITEM_VENDA_ID
UPDATE TBL_PAGAMENTO SET PAG_DINHEIRO -= @VALORREMOVER WHERE VENDA_ID = @VENDAID
UPDATE TBL_PRODUTO SET PROD_QTD += @QTDREMOVER WHERE PROD_ID = @PRODID
END

ELSE IF(@QTDREMOVER = @QTD_TOTAL_ITEM)
BEGIN
DELETE TBL_ITEM_VENDA WHERE VEN_ID = @VENDAID AND PROD_ID = @PRODID AND ITEM_VENDA_ID = @ITEM_VENDA_ID
UPDATE TBL_PAGAMENTO SET PAG_DINHEIRO -= @VALORREMOVER WHERE VENDA_ID = @VENDAID
UPDATE TBL_PRODUTO SET PROD_QTD += @QTDREMOVER WHERE PROD_ID = @PRODID
END

--ELSE IF(@VALOR_TOTAL_VENDA = @VALORREMOVER)
--BEGIN
--DELETE TBL_PAGAMENTO WHERE VENDA_ID = @VENDAID
--DELETE TBL_ITEM_VENDA WHERE VEN_ID = @VENDAID AND PROD_ID = @PRODID
--UPDATE TBL_PRODUTO SET PROD_QTD += @QTDREMOVER WHERE PROD_ID = @PRODID
--END

--DECLARE @VENDTOTAL DECIMAL(10,2)=(SELECT VEN_TOTAL FROM TBL_VENDA WHERE VEN_ID = @VENDAID)
--IF(@VENDTOTAL = 0.00)
--BEGIN
--DELETE TBL_VENDA WHERE VEN_ID = @VENDAID
--END

GO



-->>>>
create PROCEDURE p_SELECT_VENDA(@ID_VENDA AS INT)
 AS
 SELECT IV.ITEM_VENDA_ID, P.PROD_ID, P.PROD_NOME,IV.ITEM_QTD, IV.ITEM_VALOR,
 V.VEN_DATE FROM TBL_CLIENTE AS C 
 INNER JOIN TBL_VENDA AS V ON V.CLI_ID = C.CLI_ID 
 INNER JOIN TBL_ITEM_VENDA AS IV ON IV.VEN_ID = V.VEN_ID
 INNER JOIN TBL_PRODUTO AS P ON P.PROD_ID = IV.PROD_ID 
 WHERE V.VEN_ID = @ID_VENDA ORDER BY  V.VEN_DATE DESC
GO






exec p_REMOVER_ITEM @NOME_CLIENTE='CLIENTE-1',
                    @VENDAID = 2,
					@PRODID =  2,
					@QTDREMOVER =1,
					@QTD_TOTAL_ITEM = 1,
					@VALOR_TOTAL_VENDA = 20.00,
					@VALOR_TOTAL_ITEM = 10.00,
					@ITEM_VENDA_ID = 3
