USE MERCADO_01 
GO

CREATE TABLE TBL_PAGAMENTO (
PAG_ID INT NOT NULL IDENTITY(1,1),
VENDA_ID INT, 
PAG_DEBITO DECIMAL(10,2) NULL,
PAG_CREDITO DECIMAL(10,2) NULL,
PAG_DINHEIRO DECIMAL(10,2) NULL,
PAG_CREDIARIO DECIMAL(10,2) NULL,
PAG_TOTAL DECIMAL(10,2) NULL
)
GO


--PRIMARY KEY
ALTER TABLE TBL_PAGAMENTO ADD CONSTRAINT PK_PAGAMENTO_ID PRIMARY KEY (PAG_ID)
GO
--FOREIGN KEY
ALTER TABLE TBL_PAGAMENTO ADD CONSTRAINT FK_PAG_VENDA_ID FOREIGN KEY (VENDA_ID) REFERENCES TBL_VENDA
GO

ALTER TABLE TBL_VENDA ALTER COLUMN VEN_PAGAMENTO VARCHAR(50)
